/*
 * Copyright (C) 2010, Broadcom Corporation
 * All Rights Reserved.
 * 
 * THIS SOFTWARE IS OFFERED "AS IS", AND BROADCOM GRANTS NO WARRANTIES OF ANY
 * KIND, EXPRESS OR IMPLIED, BY STATUTE, COMMUNICATION OR OTHERWISE. BROADCOM
 * SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A SPECIFIC PURPOSE OR NONINFRINGEMENT CONCERNING THIS SOFTWARE.
 *
 * $Id: epivers.h.in,v 13.32 2009-11-04 00:51:53 Exp $
 *
*/

#ifndef _epivers_h_
#define _epivers_h_

#define	EPI_MAJOR_VERSION	5

#define	EPI_MINOR_VERSION	100

#define	EPI_RC_NUMBER		82

#define	EPI_INCREMENTAL_NUMBER	112

#define	EPI_BUILD_NUMBER	0

#define	EPI_VERSION		5, 100, 82, 112

#define	EPI_VERSION_NUM		0x05645270

#define EPI_VERSION_DEV		5.100.82

#define	EPI_VERSION_STR		"5.100.82.112"

#endif 
